from __future__ import annotations

from ..config import DATA_DIR
from .connection import (
    _escape_like,
    DEFAULT_DB_PATH,
    DEFAULT_DIALOGUE_DB_PATH,
    get_data_dir,
    get_db,
    get_db_path,
    get_dialogue_db,
    get_dialogue_db_path,
    set_db_path,
    set_dialogue_db_path,
)
from .dialogues import (
    BACK_MATTER_MEAN_LINE_CHARS,
    BACK_MATTER_PAGES,
    DIALOGUE_KIND,
    DIALOGUE_RECENT_WINDOW_DAYS,
    DIALOGUE_SIGNAL_WEIGHTS,
    FRONT_MATTER_PAGES,
    MAX_PAGE_BOXES,
    MIN_PAGES_FOR_POSITION_RULE,
    PARATEXT_KIND,
    STORY_CONTEXT_MAX_LINES,
    STORY_CONTEXT_MAX_PAGES,
    _ASCII_LOWER,
    _CJK_RE,
    _PARATEXT_RE,
    _SCANLATOR_RE,
    _VECTOR_CACHE,
    _bump_vector_version,
    _coerce_order_index,
    _comic_signals,
    _dialogue_book_fields,
    _dialogue_comics_meta_map,
    _dialogue_key,
    _is_noise_line,
    _make_snippet,
    _normalize_box,
    _parse_metric_count,
    _rank_dialogue_pages,
    _safe_json_list,
    _vector_status,
    _vector_store,
    classify_dialogue_kind,
    cleanup_orphan_comic_dialogues,
    delete_comic_dialogues,
    dialogue_vector_status,
    embed_comic_dialogues,
    get_story_context,
    rebuild_dialogue_vectors,
    search_dialogues,
    search_dialogues_semantic,
    sync_comic_dialogues,
)
from .index import (
    _apply_facets_delta,
    _compute_library_facets,
    _copy_facets,
    _facets_cache,
    _facets_cache_lock,
    _facets_compute_lock,
    _last_facets_invalidated_at,
    batch_find_comic_mirrors,
    delete_comic_index,
    find_comic_mirrors,
    get_all_indexed_mtimes,
    get_comic_index_count,
    get_comics_due_for_auto_update,
    get_library_facets,
    invalidate_facets_cache,
    purge_comic_db_records,
    query_library_index,
    rebuild_facets_snapshot,
    record_comic_auto_checked,
    update_comic_cached_pages,
    upsert_comic_index,
)
from .passes import (
    _INVISIBLE_OR_OVERRIDE_CHARS,
    _device_register_lock,
    _row_to_pass,
    claim_guest_pass,
    clean_expired_direct_passes,
    create_direct_pass,
    create_guest_pass,
    delete_guest_device,
    delete_guest_pass,
    get_device_by_token,
    get_direct_pass,
    get_guest_pass_by_id,
    get_guest_pass_by_token,
    hash_pin,
    list_guest_passes,
    parse_device_name,
    register_guest_device,
    sanitize_username,
    touch_device_active,
    update_guest_pass,
    verify_guest_pass_pin,
    verify_pin,
)
from .schema import (
    _CREATE_DIALOGUES_FTS,
    _DIALOGUE_COLUMNS,
    _migrate_dialogue_schema,
    backfill_dialogue_index,
    init_db,
    init_dialogue_db,
)
from .user_state import (
    get_user_favorites,
    get_user_progress,
    is_user_favorite,
    migrate_legacy_favorites,
    set_user_favorite,
    set_user_progress,
)

__all__ = [
    # Config & Constants
    "DATA_DIR",
    "_DB_PATH",
    "_DIALOGUE_DB_PATH",
    "_escape_like",
    "DEFAULT_DB_PATH",
    "DEFAULT_DIALOGUE_DB_PATH",
    "MAX_PAGE_BOXES",
    "DIALOGUE_KIND",
    "PARATEXT_KIND",
    "FRONT_MATTER_PAGES",
    "BACK_MATTER_PAGES",
    "MIN_PAGES_FOR_POSITION_RULE",
    "BACK_MATTER_MEAN_LINE_CHARS",
    "STORY_CONTEXT_MAX_LINES",
    "STORY_CONTEXT_MAX_PAGES",
    "DIALOGUE_SIGNAL_WEIGHTS",
    "DIALOGUE_RECENT_WINDOW_DAYS",
    # Connection
    "get_data_dir",
    "get_db",
    "get_dialogue_db",
    "get_db_path",
    "get_dialogue_db_path",
    "set_db_path",
    "set_dialogue_db_path",
    # Schema
    "init_db",
    "init_dialogue_db",
    "_migrate_dialogue_schema",
    "backfill_dialogue_index",
    # Passes & Auth
    "hash_pin",
    "verify_pin",
    "sanitize_username",
    "parse_device_name",
    "_row_to_pass",
    "create_guest_pass",
    "claim_guest_pass",
    "verify_guest_pass_pin",
    "list_guest_passes",
    "get_guest_pass_by_id",
    "get_guest_pass_by_token",
    "update_guest_pass",
    "delete_guest_pass",
    "register_guest_device",
    "get_device_by_token",
    "touch_device_active",
    "delete_guest_device",
    "create_direct_pass",
    "get_direct_pass",
    "clean_expired_direct_passes",
    # User State
    "get_user_favorites",
    "is_user_favorite",
    "set_user_favorite",
    "migrate_legacy_favorites",
    "get_user_progress",
    "set_user_progress",
    # Index & Facets
    "invalidate_facets_cache",
    "rebuild_facets_snapshot",
    "_apply_facets_delta",
    "upsert_comic_index",
    "purge_comic_db_records",
    "delete_comic_index",
    "get_all_indexed_mtimes",
    "get_comic_index_count",
    "update_comic_cached_pages",
    "get_comics_due_for_auto_update",
    "record_comic_auto_checked",
    "find_comic_mirrors",
    "batch_find_comic_mirrors",
    "query_library_index",
    "_compute_library_facets",
    "_copy_facets",
    "get_library_facets",
    # Dialogues & FTS
    "_normalize_box",
    "_coerce_order_index",
    "_make_snippet",
    "_is_noise_line",
    "classify_dialogue_kind",
    "_dialogue_key",
    "sync_comic_dialogues",
    "delete_comic_dialogues",
    "_dialogue_comics_meta_map",
    "embed_comic_dialogues",
    "rebuild_dialogue_vectors",
    "_vector_status",
    "dialogue_vector_status",
    "_bump_vector_version",
    "_vector_store",
    "search_dialogues_semantic",
    "_safe_json_list",
    "_dialogue_book_fields",
    "cleanup_orphan_comic_dialogues",
    "_parse_metric_count",
    "search_dialogues",
    "_comic_signals",
    "_rank_dialogue_pages",
    "get_story_context",
]


def __getattr__(name: str):
    """PEP 562 模块级动态属性解析（只读向后兼容）。

    注意：测试或运行时若需切换数据库路径，必须调用 set_db_path() / set_dialogue_db_path()，
    严禁直接对模块属性 db._DB_PATH 赋值（直接赋值会绕过连接池并导致测试隔离失效，见 PITFALLS #160）。
    """
    if name == "_DB_PATH":
        return get_db_path()
    if name == "_DIALOGUE_DB_PATH":
        return get_dialogue_db_path()
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

