export type IconPresetSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl'
export type IconSize = IconPresetSize | number | (string & {})

export type IconName =
  | 'close'
  | 'check'
  | 'heart'
  | 'heart-filled'
  | 'search'
  | 'info'
  | 'more'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up'
  | 'chevron-down'
  | 'upload'
  | 'download'
  | 'camera'
  | 'external-link'
  | 'refresh'
  | 'plus'
  | 'minus'
  | 'lock'
  | 'unlock'
  | 'book-open'
  | 'eye'
  | 'eye-off'
  | 'archive'
  | 'trash'
  | 'users'
  | 'copy'
  | 'logout'
